[workspace]
channels = ["conda-forge"]
name = "pp2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bear = ">=3.1.6,<4"
clang-tools = ">=21.1.1,<22"
polars-lts-cpu = ">=1.5.0,<2"
matplotlib = ">=3.9.2,<4"
parallel = ">=20250822,<20250823"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.3.3,<3"
